"""Evidence integrity tables

Evidence bundles, chain of custody and integrity baselines moved out of
module-level dicts. These features exist to be trustworthy after the fact, so
losing them on restart is worse than not offering them: the chain reports a
complete history right up to the moment it silently becomes empty.

Revision ID: 004
Revises: 003
Create Date: 2026-08-17
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_integrity',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_asset_integrity_asset')
    )
    op.create_table('custody_events',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Enum('viewed', 'downloaded', 'exported', 'modified', 'shared', 'deleted', name='custodyaction'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custody_events_asset_timestamp', 'custody_events', ['asset_id', 'timestamp'], unique=False)
    op.create_table('evidence_bundles',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('alert_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_bundles_alert', 'evidence_bundles', ['alert_id'], unique=False)
    op.create_index('ix_evidence_bundles_workspace', 'evidence_bundles', ['workspace_id'], unique=False)
    op.create_table('evidence_bundle_items',
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['evidence_bundles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_bundle_items_bundle', 'evidence_bundle_items', ['bundle_id'], unique=False)


def downgrade() -> None:
    op.drop_table('evidence_bundle_items')
    op.drop_table('evidence_bundles')
    op.drop_table('custody_events')
    op.drop_table('asset_integrity')
