"""Plugin and marketplace persistence

Plugin registrations, marketplace installs, plugin reviews, custom pipeline
nodes, BYOM model registrations and inference adapters moved off module-level
dicts. A plugin registration that vanishes on restart takes its pipelines with
it: a step referencing a custom node stops resolving, and an installed
marketplace plugin silently un-installs itself.

The loaded model objects themselves stay in a per-process cache — they are
live handles rather than data — but the registration saying where to load them
from is now a row.

Revision ID: 005
Revises: 004
Create Date: 2026-08-17
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('byom_models',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('input_shape', sa.String(length=100), nullable=False),
    sa.Column('output_shape', sa.String(length=100), nullable=False),
    sa.Column('adapter', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=True),
    sa.Column('node_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'model_name', name='uq_byom_workspace_model_name')
    )
    op.create_index('ix_byom_models_workspace', 'byom_models', ['workspace_id'], unique=False)
    op.create_table('custom_nodes',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custom_nodes_workspace', 'custom_nodes', ['workspace_id'], unique=False)
    op.create_table('installed_plugins',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('latest_version', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('used_in_pipelines', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_installed_plugins_workspace', 'installed_plugins', ['workspace_id'], unique=False)
    op.create_table('model_adapters',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_path_or_url', sa.String(length=1000), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('input_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_adapters_workspace', 'model_adapters', ['workspace_id'], unique=False)
    op.create_table('plugins',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('entry_point', sa.String(length=500), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('config_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugins_workspace', 'plugins', ['workspace_id'], unique=False)
    op.create_table('plugin_reviews',
    sa.Column('plugin_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_reviews_plugin', 'plugin_reviews', ['plugin_id'], unique=False)


def downgrade() -> None:
    op.drop_table('plugin_reviews')
    op.drop_table('plugins')
    op.drop_table('model_adapters')
    op.drop_table('installed_plugins')
    op.drop_table('custom_nodes')
    op.drop_table('byom_models')
