"""Mobile and integration persistence

Push registrations, notification preferences, offline sync conflicts, field
location tracks, webhook registrations, webhook delivery history and the
event-bus log moved off module-level dicts.

A push registration lost on restart means the operator stops receiving alerts
and nothing reports an error. An unresolved sync conflict lost on restart
silently discards one side of an edit made in the field. A webhook
registration lost on restart stops an integration firing with nothing left to
show it was ever configured.

Revision ID: 006
Revises: 005
Create Date: 2026-08-17
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_bus_log',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_bus_log_workspace_timestamp', 'event_bus_log', ['workspace_id', 'timestamp'], unique=False)
    op.create_table('field_locations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_ref', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_locations_user_timestamp', 'field_locations', ['user_ref', 'timestamp'], unique=False)
    op.create_table('push_devices',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_ref', sa.String(length=64), nullable=False),
    sa.Column('device_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_ref', 'device_token', name='uq_push_device_token')
    )
    op.create_index('ix_push_devices_user', 'push_devices', ['user_ref'], unique=False)
    op.create_table('push_preferences',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_ref', sa.String(length=64), nullable=False),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_ref', name='uq_push_preferences_user')
    )
    op.create_table('sync_conflicts',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('local_version', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('server_version', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_conflicts_workspace', 'sync_conflicts', ['workspace_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhooks_workspace', 'webhooks', ['workspace_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_webhook_timestamp', 'webhook_deliveries', ['webhook_id', 'timestamp'], unique=False)


def downgrade() -> None:
    op.drop_table('webhook_deliveries')
    op.drop_table('webhooks')
    op.drop_table('sync_conflicts')
    op.drop_table('push_preferences')
    op.drop_table('push_devices')
    op.drop_table('field_locations')
    op.drop_table('event_bus_log')
