"use client";

import { useCallback, useEffect, useRef, useState } from "react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AnnotationType = "BBOX" | "POLYGON" | "KEYPOINT" | "LABEL";

export interface Annotation {
  id: string;
  label: string;
  type: AnnotationType;
  color: string;
  coordinates: Record<string, unknown>;
  confidence?: number;
  /** True when the annotation was generated by an AI model. */
  aiSuggested?: boolean;
}

type SaveStatus = "saved" | "unsaved" | "saving";

interface AnnotationListPanelProps {
  annotations: Annotation[];
  onSelect: (id: string) => void;
  onDelete: (id: string) => void;
  assetId: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const TYPE_BADGE: Record<AnnotationType, string> = {
  BBOX: "bg-blue-100 text-blue-700",
  POLYGON: "bg-green-100 text-green-700",
  KEYPOINT: "bg-purple-100 text-purple-700",
  LABEL: "bg-yellow-100 text-yellow-700",
};

function coordinatesSummary(type: AnnotationType, coords: Record<string, unknown>): string {
  switch (type) {
    case "BBOX": {
      const x = Math.round(Number(coords.x ?? 0));
      const y = Math.round(Number(coords.y ?? 0));
      const w = Math.round(Number(coords.width ?? 0));
      const h = Math.round(Number(coords.height ?? 0));
      return `(${x},${y}) ${w}x${h}`;
    }
    case "POLYGON": {
      const pts = coords.points as unknown[] | undefined;
      return `${pts?.length ?? 0} pts`;
    }
    case "KEYPOINT": {
      const kps = coords.points as unknown[] | undefined;
      return `${kps?.length ?? 0} kps`;
    }
    case "LABEL":
      return "";
    default:
      return "";
  }
}

// ---------------------------------------------------------------------------
// Auto-save hook (debounced 2 s)
// ---------------------------------------------------------------------------

function useAutoSave(
  annotations: Annotation[],
  assetId: string,
  debounceMs = 2000,
): SaveStatus {
  const [status, setStatus] = useState<SaveStatus>("saved");
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const prevRef = useRef<string>("");

  const save = useCallback(async () => {
    setStatus("saving");
    try {
      await fetch("/api/annotate/save", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ asset_id: assetId, annotations }),
      });
      setStatus("saved");
    } catch {
      setStatus("unsaved");
    }
  }, [annotations, assetId]);

  useEffect(() => {
    const serialised = JSON.stringify({ assetId, annotations });
    if (serialised === prevRef.current) return;
    prevRef.current = serialised;

    // Skip auto-save for the very first render (initial load)
    if (status === "saved" && timerRef.current === null) {
      timerRef.current = undefined as unknown as ReturnType<typeof setTimeout>;
      return;
    }

    setStatus("unsaved");

    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => {
      void save();
    }, debounceMs);

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [annotations, assetId, debounceMs, save, status]);

  return status;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function AnnotationListPanel({
  annotations,
  onSelect,
  onDelete,
  assetId,
}: AnnotationListPanelProps) {
  const [hoveredId, setHoveredId] = useState<string | null>(null);
  const saveStatus = useAutoSave(annotations, assetId);

  return (
    <div className="flex flex-col h-full border-l border-gray-200 bg-white">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200">
        <h3 className="text-sm font-semibold text-gray-900">
          Annotations ({annotations.length})
        </h3>
        <SaveIndicator status={saveStatus} />
      </div>

      {/* List */}
      <div className="flex-1 overflow-y-auto">
        {annotations.length === 0 ? (
          <div className="px-4 py-8 text-center text-sm text-gray-400 italic">
            No annotations yet.
          </div>
        ) : (
          <ul className="divide-y divide-gray-100">
            {annotations.map((ann) => (
              <li
                key={ann.id}
                onClick={() => onSelect(ann.id)}
                onMouseEnter={() => setHoveredId(ann.id)}
                onMouseLeave={() => setHoveredId(null)}
                className="flex items-center gap-3 px-4 py-2.5 cursor-pointer transition-colors hover:bg-gray-50"
              >
                {/* Color swatch */}
                <span
                  className="flex-shrink-0 w-3 h-3 rounded-sm border border-gray-300"
                  style={{ backgroundColor: ann.color }}
                />

                {/* Label + type badge + coords */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-gray-800 truncate">
                      {ann.label}
                    </span>
                    <span
                      className={`px-1.5 py-0.5 rounded text-[10px] font-medium uppercase ${
                        TYPE_BADGE[ann.type] ?? "bg-gray-100 text-gray-600"
                      }`}
                    >
                      {ann.type}
                    </span>
                  </div>

                  <div className="flex items-center gap-2 mt-0.5">
                    {coordinatesSummary(ann.type, ann.coordinates) && (
                      <span className="text-xs text-gray-500">
                        {coordinatesSummary(ann.type, ann.coordinates)}
                      </span>
                    )}
                    {ann.confidence !== undefined && (
                      <span className="text-xs text-indigo-500 font-medium">
                        {(ann.confidence * 100).toFixed(0)}% AI
                      </span>
                    )}
                  </div>
                </div>

                {/* Hover actions */}
                {hoveredId === ann.id && (
                  <div className="flex items-center gap-1 flex-shrink-0">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        onSelect(ann.id);
                      }}
                      className="p-1 rounded hover:bg-gray-200 text-gray-500"
                      title="Edit"
                    >
                      <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                        />
                      </svg>
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        onDelete(ann.id);
                      }}
                      className="p-1 rounded hover:bg-red-100 text-red-400 hover:text-red-600"
                      title="Delete"
                    >
                      <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                        />
                      </svg>
                    </button>
                  </div>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Save indicator sub-component
// ---------------------------------------------------------------------------

function SaveIndicator({ status }: { status: SaveStatus }) {
  switch (status) {
    case "saved":
      return (
        <span className="flex items-center gap-1 text-xs text-green-600">
          <span className="inline-block w-2 h-2 rounded-full bg-green-500" />
          Saved
        </span>
      );
    case "unsaved":
      return (
        <span className="flex items-center gap-1 text-xs text-amber-600">
          <span className="inline-block w-2 h-2 rounded-full bg-amber-400 border border-amber-500" />
          Unsaved
        </span>
      );
    case "saving":
      return (
        <span className="flex items-center gap-1 text-xs text-gray-500">
          <span className="inline-block w-2 h-2 rounded-full bg-gray-400 animate-pulse" />
          Saving...
        </span>
      );
  }
}
